
server:
  port: 8082
spring:
  application:
    name: tags-service
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://root:root@mongodb:27017/notesdb?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/notes-realm
management:
    endpoints:
        web:
          exposure:
            include: health,info,metrics,env

eureka:
  client:
    service-url:
      defaultZone: http://naming-server-notes:8671/eureka